### ISSUE TITLE
Row and colomns are not increamenting

### ISSUE THREAD

**Issue by hardikhere** [hardikhere/hacktoberfest#1]

**Comment by chandresh189** [comment]
I am working on it

**Comment by AmirHMaleki** [comment]
Hey, can I help?

**Comment by hardikhere** [comment]
> Hey, can I help?

of course

**Comment by divyaSathya13** [comment]
Can I help with this issue?

**Comment by hardikhere** [comment]
> Can I help with this issue?

Thanks Divya but I am closing this issue I am adding some more file with errors, try those.
